import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ClientWrapper from "./ClientWrapper";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Rwikistat Web App",
  description: "Generated by create next app",
  verification: {
    google: "11Xtq9cHvNyWjdeZUEQJriO-737INPZVdPCkjC8LTpc",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="antialiased bg-white text-gray-900 tracking-tight">
        <ClientWrapper>
          <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip font-poppins">
            {children}
          </div>
        </ClientWrapper>
      </body>
    </html>
  );
}
